name: Kral

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 999999999999

    steps:

    - name: 1. Ngrok Indiriliyor...

      run: |

        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

        Invoke-WebRequest https://raw.githubusercontent.com/FFFrreeaakk/VDS/main/start.bat -OutFile start.bat

        Invoke-WebRequest https://raw.githubusercontent.com/FFFrreeaakk/VDS/main/wallpaper.jpg -OutFile wallpaper.jpg

        Invoke-WebRequest https://raw.githubusercontent.com/FFFrreeaakk/VDS/main/wallpaper.bat -OutFile wallpaper.bat

    - name: 2. Ngrok Dosya Cikariyor...

      run: Expand-Archive ngrok.zip

    - name: 3. Ngrok hesaba baglaniyor...

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: 4. RDP erisimi etkinlestiriliyor...

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

        copy wallpaper.jpg D:\a\wallpaper.jpg

        copy wallpaper.bat D:\a\wallpaper.bat

    - name: 5. Tünel Oluşturma.

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'

    - name: 6. RDP nize baglaniyor...

      run: cmd /c start.bat

    - name: 7. RDP basladi!

      run: | 

        Invoke-WebRequest https://raw.githubusercontent.com/FFFrreeaakk/VDS/main/loop.ps1 -OutFile loop.ps1

        ./loop.ps1
